<?php
/**
 * µMenu module.
 */

/**
 * Implements hook_theme().
 */
function umenu_theme() {
  return [
    'umenu' => [
      'variables' => ['tree' => null, 'name' => null, 'current' => null],
      'template' => 'umenu',
    ],
  ];
}

/**
 * Implements template_preprocess_HOOK().
 */
function template_preprocess_umenu(&$variables) {
  if (isset($variables['name'])) {
    $variables['theme_hook_suggestions'][] = 'umenu__' . str_replace('-', '_', $variables['name']);
  }
  /*
  if ($hook !== $variables['theme_hook_original']) {
    $variables['theme_hook_suggestions'][] = $variables['theme_hook_original'];
    if (isset($variables['name'])) {
      $variables['theme_hook_suggestions'][] = $variables['theme_hook_original'] . '__' . str_replace('-', '_', $variables['name']);
    }
  }
   */
  if (!isset($variables['current'])) {
    /* if ($node = menu_get_object()) {
      $variables['current'] = $node->nid;
    } */
  }
}
